name: Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Выберите тип билда'
        required: false
        default: 'preview'
        type: choice
        options:
          - preview
          - publish
  # schedule:
  #   - cron: '0 1 * * *' # 1:00 UTC каждый день

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Без этой строки скачается вся история    

      # Запуск всей логики через один Python скрипт
      - name: Run Pipeline Script
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Токен нужен для gh CLI внутри питона
          PYTHONUTF8: 1  # <-- ДОБАВЬТЕ ЭТУ СТРОКУ
        run: |
          python .github/workflows/build_logic.py "${{ github.event.inputs.build_type }}"

      - uses: actions/upload-artifact@v4
        if: ${{ build_type == 'preview' }}
        with:
          if-no-files-found: error
          name: "night_build_${{ github.sha }}"
          path: "*.zip"   
            